name: condition

on: [push]
jobs:
  condition:
    runs-on: ubuntu-latest
    steps:
      - name: Check condition
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "This is a push event."
          else
            echo "This is not a push event."
          fi
        
      - name : trigger PROD environment
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Triggering PROD environment..."
        
      - name : trigger dev environment
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: |
          echo "Triggering dev environment..."
        